### ISSUE TITLE
ConfigMap is not created on custom environments and own domain

### ISSUE THREAD

**Issue by khell** [jenkins-x/exposecontroller#161]
`jx install --no-default-environments --domain wildcard.example.com` on a brand new AKS cluster, followed by for example `jx create environment canary --git-provider-url=https://bitbucket.org --pull-secrets='private-registry-secret'` does not create a ConfigMap entry for `exposecontroller` in the new environment's namespace. When deploying, this results in this error:

```
exposecontroller.go:194] failed to create new strategy: failed to create auto expose strategy: failed to get a domain: no known automatic ways to get an external ip to use with nip.  Please configure exposecontroller configmap manually see https://github.com/jenkins-x/exposecontroller#configuration
```

I had to manually add the ConfigMap:
```yaml
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    provider: "fabric8"
    project: "exposecontroller"
  name: "exposecontroller"
  namespace: jx-canary
data:
  config.yml: |-
    domain: wildcard.example.com
    exposer: Ingress
```

Also the expose ServiceAccount did not have the correct permissions...
