### ISSUE TITLE
Openshift - expose multiple applications under the same domain name

### ISSUE THREAD

**Issue by gcontini** [jenkins-x/exposecontroller#177]
I'm not sure it's a documentation bug, or it's really not supported.
I'm running on openshift, I want to expose two applications under the same hostname and different path. 
This is my exposecontroller configmap:
```
	exposer: "Route"
        domain: "jx-staging.router.default.svc.cluster.local"
        watch-current-namespace: true
        http: true
```

These are my service annotations:
```
    fabric8.io/expose: 'true'
    fabric8.io/ingress.path: '/app1/'
    fabric8.io/route-host: 'jx-staging.router.default.svc.cluster.local'
    fabric8.io/route-use-path: 'true'
```

If it is supported please consider update documentation or add one example to explain how to do it...

**Comment by gcontini** [comment]
I forgot to say, what i get is the application exposed at:
http://app1-jx-staging.router.default.svc.cluster.local
(if app1 is the name of the application)

**Comment by gcontini** [comment]
It magically started working... i haven't found out why yet. however it's not easy to find the right annotations. Please document the Openshift case better.

**Comment by roxxette** [comment]
Hi Contini,

I succeeded with exposer config. I didn't try service annotations, I assume it's a similar issue.

First, by reading charts [configmap.yaml](https://github.com/jenkins-x/exposecontroller/blob/master/charts/exposecontroller/templates/configmap.yaml)

You have to configure route-host as extravalues
```
    exposer: "Route"
    domain: "jx-staging.router.default.svc.cluster.local"
    http: true
    extravalues:
      watch-current-namespace: true
      route-use-path: true
      route-host: "jx-staging.router.default.svc.cluster.local"
```

Sencond, you'll meet error in exposer: 'Add failed: failed to create route ...: spec.host: Forbidden: you do not have permission to set the host field of the route'
This is caused by lack of certain permission in apigroup 'route.openshift.io'.  Refer to [PR #185 ](https://github.com/jenkins-x/exposecontroller/pull/185) for detail.

Regards,
Rox
