### ISSUE TITLE
All Ingresses have the same secretName after jx upgrade ingress

### ISSUE THREAD

**Issue by wenzlaff** [jenkins-x/exposecontroller#182]
The command jx upgrade ingress recently seems to have some problems with handling TLS secrets. Currently all ingresses (jenkins, dockerregistry, …) are created with the same tls-secret (e.g. tls-docker-registry). 

jenkins:
```
  tls:
  - hosts:
    - jenkins.jx.example.com
    secretName: tls-docker-registry
```
docker-registry:
```
  tls:
  - hosts:
    - docker-registry.jx.example.com
    secretName: tls-docker-registry
```
