### ISSUE TITLE
Annotations do not change ingress hostname

### ISSUE THREAD

**Issue by macalinao** [jenkins-x/exposecontroller#183]
Hey all, how do I change the ingress "host" using exposecontroller annotations?

```
  "spec": {
    "rules": [
      {
        "host": "my-service.jx-staging.myhost.com",
        "http": {
          "paths": [
            {
              "backend": {
                "serviceName": "my-service",
                "servicePort": 80
              }
            }
          ]
        }
      }
    ]
  },
```

is what exists, but I want

```
  "spec": {
    "rules": [
      {
        "host": "custom-host.myhost.com",
        "http": {
          "paths": [
            {
              "backend": {
                "serviceName": "my-service",
                "servicePort": 80
              }
            }
          ]
        }
      }
    ]
  },
```

Right now, I have:

```
  service:
    annotations:
      fabric8.io/ingress.name: my-service
      fabric8.io/exposeUrl: http://custom-host.myhost.com
      osiris.deislabs.io/ingressHostname: custom-host.myhost.com
      fabric8.io/exposeHostNameAs: osiris.deislabs.io/ingressHostname
```

but it doesn't seem to be working. Any ideas? Thanks!
