### ISSUE TITLE
use exposecontroller to expose services on a separate internal ingress

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/exposecontroller#197]
We have some applications that we'd only like to be available within VPC and not exposed publicly. So we created another nginx ingress with the following config:

```yaml
controller:
  replicaCount: 2
  publishService:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    externalTrafficPolicy: Local
  ingressClass: nginx-internal
```
and then if we map the internal loadbalancer to a private hosted zone, `company.internal` and setup the right ingress config;

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  name: internal-service
  namespace: jx-staging
spec:
  rules:
  - host: internal-service.jx-staging.company.internal
    http:
      paths:
      - backend:
          serviceName: internal-service
          servicePort: 443
```

the service is available just within VPC as expected. But it would be nice if we can automate creation of this ingress just like for public ingress objects.

I did try to go through the code for exposecontroller and jenkins-x/jx to figure out the changes that need to be made. Can someone from the jenkins-x team please provide some pointers on how to proceed?
