### ISSUE TITLE
Issue with `tlsSecretName`

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/exposecontroller#204]
Hello,

I cannot use `expose.config.tls-secret-name` in values.yaml of preview chart because of:

https://github.com/jenkins-x/exposecontroller/blob/3cbc27dca3bf87cb28e3c3ff53e91658fe76f4ee/exposestrategy/ingress.go#L181

This overwrites the argument.

Also, I have question regarding `expose.config.tlsacme` and `expose.config.tls-acme`. Regarding https://github.com/jenkins-x/exposecontroller/blob/3cbc27dca3bf87cb28e3c3ff53e91658fe76f4ee/controller/config.go#L63 the second is right, but if I comment out `expose.config.tlsacme` in the values.yaml then TLS mode is not enabled. Why?

I use `version: 2.3.118` or exposecontroller chart.

**Comment by stepanselyuk** [comment]
So now to fix this issue I use this construction (`jenkins-x.yaml`):

```yaml
buildPack: python

# see https://jenkins-x.io/docs/reference/pipeline-syntax-reference/
# see https://jenkins-x.io/docs/build-test-preview/jenkins-x-pipelines/
# see https://joostvdg.github.io/jenkinsx/build-packs/

pipelineConfig:
  pipelines:
    overrides:
      - name: jx-preview
        pipeline: pullRequest
        stage: promote
        step:
          name: jx-preview
          sh: |
            export PREVIEW_NAMESPACE=$(echo "$APP_NAME-$BRANCH_NAME" | tr '[:upper:]' '[:lower:]') \
            && export SERVICE_NAME="flask-yeelight" \
            && export SECRET_NAME="tls-k8s-myorg-p" \
            && (kubectl create ns "$PREVIEW_NAMESPACE" || true) \
            && kubectl get secret "$SECRET_NAME" --namespace="jx" --export -o yaml \
                | sed -e 's/name: '"$SECRET_NAME"'/name: tls-'"$SERVICE_NAME"'/g' \
                | kubectl apply --namespace="$PREVIEW_NAMESPACE" -f - \
            && jx preview --app "$SERVICE_NAME" --namespace "$PREVIEW_NAMESPACE"  --dir ../..
          dir: ./charts/preview
        type: replace
```
