### ISSUE TITLE
Allow static mapping from exposecontroller

### ISSUE THREAD

**Issue by wingedfox** [jenkins-x/exposecontroller#25]
As long as direct etcd configuration allows to map any service to any sub-domain it worth to add static mappings to exposecontroller.
Probably something like

``` yaml
label:
  "fabric8.io/exposecontroller/static-map-root": "true"
  "fabric8.io/exposecontroller/static-map-subdomain": "auth"
  "fabric8.io/exposecontroller/static-map-subdomain": "docs.api"
```
